services:
  bng-public-register:
    build:
      context: .
      target: production
    image: bng-public-register
    container_name: bng-public-register
    environment:
      APPINSIGHTS_CLOUDROLE: bng-public-register-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
